
# Dockerfile for StockPortfolio API

# Use a Tomcat image as the base image
FROM tomcat:9-jdk17-openjdk-slim

# Copy the WAR file into the webapps directory of Tomcat
COPY ./target/StockPortfolioAPI-0.0.1.war /usr/local/tomcat/webapps/

# Expose the default Tomcat port
EXPOSE 8085

# Start Tomcat
CMD ["catalina.sh", "run"]
